export const GET_PRODUCT = "GET_PRODUCT"
export const ADD_TO_BASKET = "ADD_TO_BASKET"
export const DELETE = "DELETE"
export const DECREASE = "DECREASE"
export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES"
export const SET_CURRENCY = "SET_CURRENCY"